- serialization_benchmarks_test.go
Use the new `Reset` function on a Builder to reduce allocs per serialize
call from 12 down to 2.
> FlatBuffers benchmark improvements

- serialization_benchmarks_test.go
```
benchmark                                      iter    time/iter   bytes/op     allocs/op  tt.time   tt.bytes       time/alloc
BenchmarkVmihailencoMsgpackMarshal           500000   2451 ns/op   352 B/op   5 allocs/op   1.23 s   17600 KB  490.20 ns/alloc
BenchmarkVmihailencoMsgpackUnmarshal         500000   2429 ns/op   347 B/op  13 allocs/op   1.21 s   17350 KB  186.85 ns/alloc
BenchmarkJsonMarshal                         300000   4234 ns/op   584 B/op   7 allocs/op   1.27 s   17520 KB  604.86 ns/alloc
BenchmarkJsonUnmarshal                       200000   6730 ns/op   447 B/op   8 allocs/op   1.35 s    8940 KB  841.25 ns/alloc
BenchmarkBsonMarshal                         500000   2475 ns/op   504 B/op  19 allocs/op   1.24 s   25200 KB  130.26 ns/alloc
BenchmarkBsonUnmarshal …
```
> Added hprose benchmarks test

- Makefile
- gencode-unsafe.schema
- gencode-unsafe.schema.gen.go
- serialization_benchmarks_test.go
If it's an option for CapNProto to have unsafe typing and such demo'd in a separate benchmark, I figured I'd add it for gencode.  As before, I haven't messed with the numbers, so you'll need to generate the results.
> Adding unsafe version of gencode

- README.md
- serialization_benchmarks_test.go
- structdef_avro.go
Fixes #64 
Should probably regenerate the report on golang 1.9 with the latest packages. I can do that as well if you feel comfortable or you can run it after merging @alecthomas
> Make goavro v1 compatible and add goavro v2 benchmark tests

- README.md
- serialization_benchmarks_test.go
I've been working on a very compact serialization library creating no-padding compact blocks that are easy to port to any other language, with some extra features like compression and custom interfaces.
In my own tests, this package has proven to consistently beat other reflection-based serialization libraries using the benchmarks provided in this PR.
Lib itself can be found here: https://github.com/ikkerens/ikeapack
> Added ikeapack to benchmarks & list

- README.md
- serialization_benchmarks_test.go
I figured I'd add this-- as I came across it on github while looking for iterative json parsers. The claim on the homepage is that it is much faster, which it seems to be ~2x faster on marshal but only ~30% faster on unmarshal.
I figured I'd submit the PR in case others want to see the numbers too
I didn't update the benchmark results on the README, as I have an X1 carbon 5th gen (so all the numbers would change).
Here is what I get:
```
BenchmarkJsonMarshal-4                   	  500000	      2959 ns/op	    1232 B/op	      10 allocs/op
BenchmarkJsonUnmarshal-4                 	  500000	      2982 ns/op	     464 B/op	       7 allocs/op
BenchmarkJsonIterMarshal-4               	 1000000	      1592 ns/op	     960 B/op	       7 allocs/op
BenchmarkJsonIterUnmarshal-4             	  500000 …
```
> Add jsoniter to benchmarks

- go.mod
- serialization_benchmarks_test.go
- structdef_avro.go
The upcomming Go version 1.13 provides benchmark metrics, which we can use to report the serial size for each format.
I need some help with the awk(1) magic in stats.sh.
> Report serial size (and errors)

- Makefile
- serialization_benchmarks_test.go
- structdef_easyjson.go
The generated easyjson code included standard encoding/json Marshaler and Unmarshaler interfaces. These will have been picked up and called by the encoding/json code and throw off the result for encoding/json (encoding/json test will have been using the easyjson code).
It's better if we generate only the easyjson-specific interfaces. The easyjson doc claims these are better.
> Easyjson test should not interfere with json test

- Makefile
- README.md
- go.mod
- go.sum
- serialization_benchmarks_test.go
- structdef-bebop-200sc.bop
- structdef-bebop-200sc.go
This PR:
- Renames 'bebop' to 'bebop-200sc' to match the new implementation's naming
- Updates 200sc/bebop to the latest version
- Switches 200sc/bebop to use a time.Time to match wellquite/bebop (NB this is slower than the former method, a unixnano uint64) 
- Notes bebop's timestamp accuracy near the other timestamp issues in the Readme
- Regenerates the Readme
> Bump 200sc/bebop to latest, standardize with other bebop implementation

- serialization_benchmarks_test.go
bpre use was removed in a previous commit, but the import lingered. This commit removes the unused import, allowing tests to run again.
> fix unused import error in benchmarks test

- serialization_benchmarks_test.go
This removes one allocation from all benchmarks that are run with the standard benchUnmarshal() function.
The allocation was for the target of the unmarshal. This is replaced with a single object used throughout the test and cleared before each test iteration.
> Remove allocation from unmarshal benchmark

- baseline.go
- serialization_benchmarks_test.go
The baseline benchmark is a hand-written serialization into a fixed sized buffer with fixed positions for the values.
It is only useful as an upper bound on what is achievable on the standard go runtime.
Results for my machine:
```
Benchmark_Baseline_Marshal       31755828          38.52 ns/op        47.00 B/serial    0 B/op   0 allocs/op
Benchmark_Baseline_Unmarshal     38182153          30.82 ns/op        47.00 B/serial    0 B/op   0 allocs/op
```
> Add baseline benchmark

- gencode.go
- mus.go
- serialization_benchmarks_test.go
This switches various bencharmarks to use the serializer interface and benchmark functions.
The following benchmarks have been switched to use the serializer interface:
- MUS
- MUSUnsafe
- Gencode
- GencodeUnsafe
> Switch to serializer tests

- baseline.go
- serialization_benchmarks_test.go
In the future, the BenchmarkCase structure will be expanded to add more information about each serializer and it will be used to dynamically generate a full HTML report.
> Use sub-benchmarks for testing

- adapter_interface.go
- baseline.go
- bebop_200sc.go
- bebop_wellquite.go
- benc.go
- capnproto.go
- colfer.go
- easyjson.go
- fastjson.go
- flatbuffers.go
- gencode.go
- gogoprotobuf.go
- goserbench/goserbench.go
- goserbench/interface.go
- hprose.go
- hprose2.go
- ike.go
- msgp.go
- mus.go
- pulsar.go
- serialization_benchmarks_test.go
- shamaton.go
- ssz.go
- structdef_avro.go
- xdr_calmh.go
This moves the actual benchmarking code into a new, isolated package. Minimal changes are made to the existing serializers in order to keep the tests working.
In the future, this will allow moving each serializer into its own package, improving overall code organization and making it clearer what code is related to each serializer.
It will also allow creating a module out of the base benchmark code, which will allow third party code (e.g. serializer packages themselves) to run the same benchmark without having to be ported to this repository.
> goserbench: Initial Version

- go.mod
- go.sum
- internal/serializers/copi/copi.go
- serialization_benchmarks_test.go
goserbench now supported copi.
please merge copi branch with master branch
> copi: a new modern high performance go serializer

- internal/serializers/ikea/ikea.go
I'm not sure why this comment was added, but it is not correct, ikeapack supports float32/float64 just fine, and always has.
The reason why I didn't use float64 for a field called Money is because using float for Money is not a good idea, and I was a little cheeky at the time :)
> Remove invalid disclaimer from ikeapack

- .github/workflows/report.yml
- README.md
Instead of using `html-previewer`, I added a github action to automatically put the contents from the report folder into the `gh-pages` branch, then the report also shows up on all browsers.
> Publishing Report to Github Pages

- report/index.html
The idea is to make it clear the results could be biased by architecture/platform or by the submitter (for example, by having it run concurrently to other workloads).
> report: Add notice about the report being user-generated

- go.mod
- go.sum
Remove unnecessary references and replacement directives.
Format the file according to the current standard formatting for go.mod files (2 sections, first with direct requirements and the second with indirect ones).
> go.mod: Tidy
